In [ ]:
# 4.1 ARRAY CREATION
# Question 1
import numpy as np

# initialize a 2x2 empty array
array = np.empty((2, 2))
print(array)

[[0. 0.]
 [0. 0.]]


In [ ]:
# Question 2
import numpy as np

# initialize a 2x2 empty array
array = np.empty((4, 2))
print(array)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Question 3
import numpy as np

shape = (2, 2)
fill_value = 7

array = np.full(shape, fill_value)
print(array)


[[7 7]
 [7 7]]


In [ ]:
# Question 4
import numpy as np

array = np.zeros_like(np.full((2,2), 7))
print(array)

[[0 0]
 [0 0]]


In [ ]:
# Question 5
import numpy as np

array = np.ones_like(np.full((2,2), 7))
print(array)

[[1 1]
 [1 1]]


In [ ]:
# Question 6
import numpy as np

new_list = [1, 2, 3, 4]

array = np.array(new_list)
print(array)


[1 2 3 4]


In [ ]:
# 4.1.1 ARRAY MANIPULATION: NUMERICAL RANGES AND ARRAY INDEXING
# Question 1
import numpy as np

array = np.arange(10, 50) # array ranging from 10 to 49
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Question 2
import numpy as np

# Creating an array ranging from 0 to 8
array = np.arange(9)

# Reshaping the array into 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Question 3
import numpy as np

# Creating a 3x3 identity matrix
identity_matrix = np.eye(3, dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Question 4
import numpy as np

# Creating random array of size 30
random_array = np.random.random(30)

# function (np.mean) for giving mean of the array
mean_value = np.mean(random_array) # mean_value = random_array.mean()

print("random array:\n", random_array)
print()
print("mean of the arrray: ", mean_value)

random array:
 [0.57004471 0.01876282 0.63821869 0.94520247 0.62583944 0.41759282
 0.28419643 0.34292411 0.70271013 0.22028956 0.29484472 0.44918593
 0.62688394 0.5307643  0.54715896 0.96736231 0.52098491 0.8237567
 0.6115497  0.21299256 0.15050082 0.05063516 0.60559984 0.25347612
 0.85633217 0.84014918 0.782581   0.52553604 0.58610823 0.7130502 ]

mean of the arrray:  0.5238411336042729


In [ ]:
# Question 5
import numpy as np

random_array = np.random.random((10, 10))

# Finding min and max value
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:\n", random_array)
print()
print("min value = ", min_value)
print("max value = ", max_value)


Random 10x10 Array:
 [[0.8314415  0.7542168  0.32914145 0.78775195 0.45616236 0.37010112
  0.50425989 0.50567729 0.12673895 0.28044221]
 [0.14899826 0.11125605 0.88883015 0.0326135  0.30149998 0.40034654
  0.48536688 0.88971039 0.69668558 0.80644575]
 [0.5632488  0.69811994 0.67084576 0.72339773 0.79397535 0.60743756
  0.28942421 0.38414097 0.24703873 0.71467926]
 [0.22577654 0.1028019  0.18324376 0.81168729 0.44175576 0.84032958
  0.39723345 0.80863421 0.79219323 0.06925835]
 [0.08753856 0.04977106 0.66924465 0.198954   0.57887912 0.71414493
  0.759435   0.45942519 0.54978951 0.90534503]
 [0.35159261 0.05944194 0.20561123 0.26941418 0.46296056 0.45618069
  0.99880236 0.72614686 0.5849856  0.82947571]
 [0.19075665 0.75326312 0.4492549  0.85008408 0.55784727 0.78138666
  0.69492798 0.7126569  0.11916395 0.92932571]
 [0.55033964 0.46542538 0.68779443 0.03975023 0.52319143 0.92959906
  0.59813907 0.47133427 0.57208484 0.51757001]
 [0.69812919 0.40020882 0.48004683 0.76671691 0.68240187 0.

In [ ]:
# Question 6
import numpy as np

# zero array of size 10
array = np.zeros(10)

# Replacing the 5th element (index 4) with 1
array[4] = 1

print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Question 7
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])  # Convert the list to a NumPy array
rev_arr = arr[::-1]  # Reverse the array using slicing

print(rev_arr)

[0 4 0 0 2 1]


In [ ]:
# Question 8
# First creating a 5x5 array with zeros
arr = np.zeros((5, 5), dtype = int)

# Setting the first and the last row as 1
arr[0, :] = 1     # sets all elements in the first row (index 0) to 1
arr[-1, :] = 1    # sets all elements in the last row.

# Setting the first and the last column as 1
arr[:, 0] = 1     # sets all elements in the first column (index 0) to 1
arr[:, -1] = 1    # sets all elements in the last column (index -1) to 1.

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# Question 9
import numpy as np

# Creating an 8x8 matrix
checkerboard = np.zeros((8, 8), dtype=int)

# Slicing in array
checkerboard[::2, ::2] = 1  # selects the even rows and col
checkerboard[1::2, 1::2] = 1  # selects the odd rows and col

# Displaying the pattern
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
# ARRAY OPERATION
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1
sum_arr = x + y
print("Sum of x and y:")
print(sum_arr)

# 2
difference_arr = x - y
print("\nDifference of x and y:")
print(difference_arr)

# 3
multiplied_arr = x * 2
print("\nx multiplied by 2:")
print(multiplied_arr)

# 4
squared_arrx = np.square(x)
print("\nSquare of each element in x:")
print(squared_arrx)

# 5
squared_arry = y ** 2
print("\nSquare of each element in x:")
print(squared_arry)

# 6
dot_product_vw = np.dot(v, w)
print("\nDot product of v and w:")
print(dot_product_vw)

dot_product_xv = np.dot(x, v)
print("\nDot product of x and v:")
print(dot_product_xv)

dot_product_xy = np.dot(x, y)
print("\nDot product of x and y:")
print(dot_product_xy)

# 7
concat_xy = np.concatenate((x, y), axis=1)
print("\nConcatenated x and y along rows:")
print(concat_xy)

concat_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenated v and w along columns:")
print(concat_vw)

# concat_xv = np.concatenate((x, v), axis=1)
# ValueError: all the input arrays must have same number of dimensions

Sum of x and y:
[[ 6  8]
 [10 13]]

Difference of x and y:
[[-4 -4]
 [-4 -3]]

x multiplied by 2:
[[ 2  4]
 [ 6 10]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Square of each element in x:
[[25 36]
 [49 64]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenated x and y along rows:
[[1 2 5 6]
 [3 5 7 8]]
Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


In [ ]:
# MATRIX OPERATIONS
import numpy as np

# 1. Prove A * A_inv = I
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
result = np.array(result, dtype=int)

print("A * A_inv = \n", result)
print()

# 2. Prove AB != BA
B = np.array([[5, 3], [2, 1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print()
print("BA = \n", BA)
print()

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T = \n", AB_T)
print()
print("B^T * A^T = \n", B_T_A_T)
print()

# 4. Solve the system of equations using inverse method
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
X = []
if(np.linalg.det(A) != 0):
    # A_inv = np.linalg.inv(A)
    # X = np.dot(A_inv, B)
    X = np.linalg.solve(A, B)
    print("Therefore X =", X)
else:
    print("The matrix is singular. can't be solved.")



A * A_inv = 
 [[1 0]
 [0 0]]

AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]

(AB)^T = 
 [[23 51]
 [13 29]]

B^T * A^T = 
 [[23 51]
 [13 29]]

Therefore X = [ 2.  1. -2.]
